### PR TITLE
feat(arco/Slider): add formatTooltip slot

### PR DESCRIPTION
**Pull request by xzdry**
image
The tooltip can now be formatted with formatTooltip slot

### CODE REVIEW

**Comment by tanbowensg** [comment]
I doubt whether it is necessary to add slot for tooltip. What do you want to put in tooltip's slot?

**Comment by xzdry** [comment]
> I doubt whether it is necessary to add slot for tooltip. What do you want to put in tooltip's slot?

**Review by tanbowensg — APPROVED** [review]
LGTM

**Comment by tanbowensg** [comment]
OK. But I think the slot name should be `tooltip`, not `formatTooltip`.

**Review by tanbowensg — CHANGES_REQUESTED** [review]
OK. But I think the slot name should be tooltip, not formatTooltip.

**Comment by xzdry** [comment]
> OK. But I think the slot name should be tooltip, not formatTooltip.

Sounds better, have changed

**Review by tanbowensg — APPROVED** [review]

**Pull request merged**
